name: setup-wabt
description: sets up the WebAssembly Binary Toolkit
inputs:
  version:
    description: toolkit version, defaults to latest
    required: false
runs:
  using: node12
  main: dist/index.js
author: Noah Anabiik Schwarz, Veikko Sariola
branding:
  icon: tool
  color: purple
